# Python Pandas Functions

Please run the imports first and keep in mind that some blocks require an absolute path csv and a DF loaded to work.

In [4]:
# Imports
import pandas as pd                                                                                 # Loads Pandas package
import os                                                                                           # For OS related paths 

#### 1. ABSOLUTE PATH FOR RAW DATA   

##### Takes: raw_data_name that should be the name of one of the csv's files 
##### Returns: a variable named csv containing the absolute path to the raw_data subfolder folder plus the name of the file in raw_data_name

In [5]:
# 1. ABSOLUTE PATH FOR RAW DATA   

def absolute_path_for_raw_data(raw_data_file):
    abspath = os.path.abspath("../raw_data")
    csv = abspath + "\\" + raw_data_file
    return csv

In [6]:
# 1. [TEST RUN] ABSOLUTE PATH FOR RAW DATA

# Current Files are Chesterfield or Leeds (comment one out)
# raw_data_file = "chesterfield_25-08-2021_09-00-00.csv"
raw_data_file = "leeds_01-01-2020_09-00-00.csv"

csv = absolute_path_for_raw_data(raw_data_file)
print(csv) # Prints the newly formed absolute path with the raw_data_file name given.


c:\Users\jzzz\Python\final-project\brewed-awakening-final-project\raw_data\leeds_01-01-2020_09-00-00.csv


### #LOADS (EXTRACT) DATAFRAME

#### Loads the df with headers .... just put outside any function

In [11]:
#LOADS (EXTRACT) DATAFRAME
columns = ['date_time', 'Location', 'full_name', 'order', 'amount', 'payment_type', 'card_number']  # Headers for the orders csv files
df = pd.read_csv(csv, header=None, names=columns)

### 2. SANITISE CSV (Remove given Columns) 

#### Takes: csv(absolute path to filename), and a list of columns to be dropped on a variable called sanatise_these_columns
#### Returns: the sanitised dataframe as df


In [12]:
# 2. SANITISE CSV (Remove given Columns) 

def sanitise_csv(csv,sanitise_these_columns):
    try:
        sanatisedf = df.drop(columns=sanitise_these_columns)
    except FileNotFoundError as fnfe:
        print(f'File not found: {fnfe}')

    return sanatisedf

In [13]:
# 2. [TEST RUN] SANITISE CSV 

# Current Files Chesterfield or Leeds (comment one out)
# raw_data_file = "chesterfield_25-08-2021_09-00-00.csv"
raw_data_file = "leeds_01-01-2020_09-00-00.csv"

columns = ['date_time', 'Location', 'full_name', 'order', 'amount', 'payment_type', 'card_number']  # Headers for the orders csv files

absolute_path_for_raw_data(raw_data_file)  # returns csv variable with the absolute path
 
sanitise_these_columns = ['full_name', 'card_number']

result = sanitise_csv(csv,sanitise_these_columns)
result.head(5)

date_time Location   
0  01/01/2020 09:00    Leeds  \
1  01/01/2020 09:01    Leeds   
2  01/01/2020 09:03    Leeds   
3  01/01/2020 09:04    Leeds   
4  01/01/2020 09:06    Leeds   

                                               order  amount payment_type  
0  Regular Chai latte - 2.30, Regular Speciality ...     3.6         CASH  
1  Large Chai latte - 2.60, Regular Filter coffee...     4.1         CARD  
2  Large Speciality Tea - English breakfast - 1.6...     2.9         CARD  
3  Large Chai latte - 2.60, Large Iced americano ...     7.6         CARD  
4                       Regular Hot Chocolate - 1.40     1.4         CARD

### 3. FILTER BY COLUMN VALUE 

#### Takes: csv(absolute path to filename), column variable with the column header id, value to check
#### Returns: the rows in which a column contains a given value AS contain_values


In [14]:
# 3. FILTER BY COLUMN VALUE 

def filter_by_column_value(csv,column,value):
    try:
        contain_values = df[df[column].str.contains(value.upper())]
    except FileNotFoundError as fnfe:
        print(f'File not found: {fnfe}')

    return contain_values

In [15]:
# 3. [TEST RUN] FILTER BY COLUMN VALUE

# Current Files Chesterfield or Leeds (comment one out)
raw_data_file = "chesterfield_25-08-2021_09-00-00.csv"
# raw_data_file = "leeds_01-01-2020_09-00-00.csv"

column = "payment_type"  
value = "card"

contain_values = filter_by_column_value(csv,column,value)
contain_values.head(10)

date_time Location         full_name   
1   01/01/2020 09:01    Leeds    Matthew Palmer  \
2   01/01/2020 09:03    Leeds     Mack Cendejas   
3   01/01/2020 09:04    Leeds   Thomas Williams   
4   01/01/2020 09:06    Leeds      Diane Ferree   
5   01/01/2020 09:08    Leeds       Bruce Watts   
6   01/01/2020 09:09    Leeds   Sergio Vanmeter   
7   01/01/2020 09:11    Leeds  Rosemary Wertman   
8   01/01/2020 09:12    Leeds      Marcia Mason   
12  01/01/2020 09:19    Leeds   Richard Redding   
13  01/01/2020 09:21    Leeds       Jean Wontor   

                                                order  amount payment_type   
1   Large Chai latte - 2.60, Regular Filter coffee...    4.10         CARD  \
2   Large Speciality Tea - English breakfast - 1.6...    2.90         CARD   
3   Large Chai latte - 2.60, Large Iced americano ...    7.60         CARD   
4                        Regular Hot Chocolate - 1.40    1.40         CARD   
5   Regular Chai latte - 2.30, Regular Filter coff...    3.80         CARD   
6   Regular Iced americano - 2.15, Regular Hot Cho...   10.75         CARD   
7   Regular Filter coffee - 1.50, Regular Hot Choc...    8.40         CARD   
8   Large Iced americano - 2.50, Regular Chai latt...    4.80         CARD   
12  Regular Hot Chocolate - 1.40, Large Filter cof...    6.85         CARD   
13  Large Speciality Tea - English breakfast - 1.6...    4.10         CARD   

     card_number  
1   5.933193e+15  
2   2.728143e+15  
3   2.992561e+15  
4   8.040887e+15  
5   2.242609e+15  
6   1.548663e+15  
7   6.706720e+15  
8   2.590703e+15  
12  4.480989e+15  
13  3.200300e+15

### 4. COUNT NUMBER OF DIFFERENT VALUES IN COLUMN 

#### Takes: csv(absolute path to filename), column variable with the column header id,
#### Returns: the count of the different values contained in a given column

In [ ]:
# 4. COUNT NUMBER OF DIFFERENT VALUES IN COLUMN 

def count_number_of_different_values(csv,column):
    try:
        count = df[column].value_counts(ascending=True)
    except FileNotFoundError as fnfe:
         print(f'File not found: {fnfe}')
    return count

In [ ]:
# 4. [TEST RUN] COUNT NUMBER OF DIFFERENT VALUES IN COLUMN 

# Current Files Chesterfield or Leeds (comment one out)
# raw_data_file = "chesterfield_25-08-2021_09-00-00.csv"
raw_data_file = "leeds_01-01-2020_09-00-00.csv"

absolute_path_for_raw_data(raw_data_file) # returns csv variable with the absolut path

column = "payment_type" 

result = count_number_of_different_values(csv,column)
print(str(result))

### 5. COUNT NUMBER OF TIMES A VALUE IS REPEATED
# 
#### Takes: csv(absolute path to filename), column variable with the column header id, value to check
#### Retuns: the count of the number of times a single value is repeated on a given column AS count


In [16]:
# 5. COUNT NUMBER OF TIMES A VALUE IS REPEATED

def count_number_of_times_a_value_is_repeated(csv,column,value):
    try:
        df = pd.read_csv(csv, header=None, names=columns)
        count = df[column].value_counts()[value]
    except FileNotFoundError as fnfe:
         return f'File not found: {fnfe}'
         
    except KeyError  as kerr:
         return f'No ocurrences of {value} in {column}' 
        
    return f"the value: {value} was found {str(count)} times."

In [17]:
# 5. [TEST RUN] COUNT NUMBER OF TIMES A VALUE IS REPEATED

# Current Files Chesterfield or Leeds (comment one out)
# raw_data_file = "chesterfield_25-08-2021_09-00-00.csv"
raw_data_file = "leeds_01-01-2020_09-00-00.csv"

absolute_path_for_raw_data(raw_data_file) # returns csv variable with the absolut path

column = "payment_type"
value = "CASH" 

result = count_number_of_times_a_value_is_repeated(csv,column,value)

print(result)



the value: CASH was found 107 times.


### 6. SAVE DATA FRAME TO FILE AS CSV

#### Takes: path for the desired save path, newfile for the desired new file name (.csv extension added at runtime)
#### Retuns: a csv file saved to the desired location that contains the DF

In [ ]:
# 6. SAVE DATA FRAME TO FILE AS CSV

def save_df_to_csv(path,newfile):
    try:
        os.makedirs(path, exist_ok=True)  
        df.to_csv(path + newfile +".csv", header=False)

    except:
        print(f'Saving operation could not be completed')


In [ ]:
# 6. [TEST RUN] SAVE DATA FRAME TO FILE AS CSV
path = "results/" # to add folder/subfolder/ if needed
newfile = "newfile"

save_df_to_csv(path,newfile)

### 7. SAVE DATAFRAME TO FILE AS JSON

#### Takes: path for the desired save path, newfile for the desired new file name (.json extension added at runtime)
#### Retuns: a csv file saved to the desired location that contains the DF

In [ ]:
# 7. SAVE DATAFRAME TO FILE AS JSON

def save_df_to_json(path,newfile):
    try:
        with open(path + newfile +".json", 'w') as f:
            f.write(df.to_json(orient='records', lines=True))  # add compression='gzip' to get a zip file (and change newfile extension)

    except:
        print(f'Saving operation could not be completed')
    


In [ ]:
# 7. [TEST RUN] SAVE DATAFRAME TO FILE AS JSON

path = "results/" # to add folder/subfolder/ if needed
newfile = "newfile"

save_df_to_json(path,newfile)

### GET UNIQUE PRODUCTS IN ORDERS
#### Returns a list with the number of  ocurrences for each product

In [18]:

# GET UNIQUE PRODUCTS IN ORDERS

def get_unique_products_in_orders():
    orders = df['order'].str.split(',', expand = True)
    
    try:
       for item in orders:
            result = orders[item].drop_duplicates()
       return result 
    
    except:
        print("Operation could not be completed.")


In [19]:
# [TEST RUN] GET UNIQUE PRODUCTS IN ORDERS


# The Current Raw csv Files are: Chesterfield or Leeds (comment one out)
raw_data_file = "chesterfield_25-08-2021_09-00-00.csv"
# raw_data_file = "leeds_01-01-2020_09-00-00.csv"


absolute_path_for_raw_data(raw_data_file)                                                           # Returns a variable called csv with the absolut path for the raw_data_file name [Run this block if fails]
columns = ['date_time', 'Location', 'full_name', 'order', 'amount', 'payment_type', 'card_number']  # Headers for the DF
df = pd.read_csv(csv, header=None, names=columns)                                                   # Creates the DF

result = ""


result = get_unique_products_in_orders()
result

0                                                   None
50                         Regular Iced americano - 2.15
55                               Large Chai latte - 2.60
57      Regular Speciality Tea - English breakfast - ...
122      Large Speciality Tea - English breakfast - 1.60
142                          Large Iced americano - 2.50
154                            Regular Chai latte - 2.30
237                         Regular Filter coffee - 1.50
Name: 5, dtype: object

In [20]:
#SEPARATE PRODUCTS IN ORDERS (string)


# the order_products string equals to a row in df['order']
# order_products = "Regular Flavoured iced latte - Hazelnut - 2.75, Large Latte - 2.45"
order_products = "Large Hot Chocolate - 1.70, Regular Hot Chocolate - 1.40, Large Chai latte - 2.60, Regular Chai latte - 2.30, Regular Speciality Tea - English breakfast - 1.30"

#LOGIC...

# A segment (named chuck in the program) is a part of the string delimited by commas (each product in the order a dash and their price)
# If a segment has two dashes then the first one will be the product name and the second will be the price
# If a segment has three dashes then the first two will be the product name and the third will be the price

chunks = order_products.split(',')

for dashes in chunks:

  if dashes.count('-') == 1:
    print(dashes[:dashes.index("-")])
    print(f"Price: " + dashes.split('-')[1])
  else: 
    stripped = dashes.split('-')[0] + "-" + dashes.split('-')[1]  #If the name contains a dash, combine it.
    print(stripped)
    print(f"Price: " + dashes.split('-')[2])


# We could use this to easily separate flavors from the drinks as well  they will be in: dashes.split('-')[1] assuming the Tea Types as flavors... #
# but that's another table to relate and probably won't be worth the trouble.  

Large Hot Chocolate 
Price:  1.70
 Regular Hot Chocolate 
Price:  1.40
 Large Chai latte 
Price:  2.60
 Regular Chai latte 
Price:  2.30
 Regular Speciality Tea - English breakfast 
Price:  1.30


In [21]:
# SEPARATE 

#SEPARATE PRODUCTS IN ORDERS WITH FLAVORS (string)


# the order_products string equals to a row in df['order']
order_products = "Regular Flavoured iced latte - Hazelnut - 2.75, Large Latte - 2.45"
# order_products = "Large Hot Chocolate - 1.70, Regular Hot Chocolate - 1.40, Large Chai latte - 2.60, Regular Chai latte - 2.30, Regular Speciality Tea - English breakfast - 1.30"

#LOGIC...

# A segment (named chuck in the program) is a part of the string delimited by commas (each product in the order a dash and their price)
# If a segment has two dashes then the first one will be the product name and the second will be the price
# If a segment has three dashes then the first two will be the product name and the third will be the price

chunks = order_products.split(',') 

for dashes in chunks:

  if dashes.count('-') == 1:
    product = dashes[:dashes.index("-")]  
    price = dashes.split('- ')[1]
    
    print(f"Product: {product}")
    print(f"Price: {price}")
    
  else: 
    product = dashes.split('-')[0]
    flavor = dashes.split('-')[1]
    price = dashes.split('-')[2] 
    
    print(f"Product: {stripped}")
    print(f"Flavor: {flavor}")
    print(f"Price: {price}")
 
    
    # With this one we can have better statistics and also count the number of flavors.
    # REMEMBER TO REMOVE THE EMPTY SPACE AFTER THE COMMA... (TYPE(LIST)) FOR PRODUCTS AND PRICE

Product:  Regular Speciality Tea - English breakfast 
Flavor:  Hazelnut 
Price:  2.75
Product:  Large Latte 
Price: 2.45


### GET NUMBER OF ROWS OF THE DATA FRAME
#### We can use any of the following methods to get the number of rows in a data frame

In [ ]:
#GET NUMBER OF ROWS OF THE DATA FRAME

# len(df.index)
# df[df.columns[0]].count()
df.shape[0]

### Check if a file exist

In [ ]:
#CHECKS IF A FILE EXIST 

file_exists = os.path.exists(csv)
print(file_exists)

### SORTING THE DATE FOR POSTGRE'S [YYYY-MM-DD H:MM:SS] FORMAT

In [ ]:

# SORTING THE DATE FOR POSTGRE'S YYYY-MM-DD H:MM:SS FORMAT

# Current Files are Chesterfield or Leeds (comment one out)
# raw_data_file = "chesterfield_25-08-2021_09-00-00.csv"
raw_data_file = "leeds_01-01-2020_09-00-00.csv"


def sort_time_to_postgre_format():
    df['date_time'] = pd.to_datetime(df['date_time'], dayfirst=True)
    
    return df



In [ ]:
# [TEST RUN] SORTING THE DATE FOR POSTGRE'S YYYY-MM-DD H:MM:SS FORMAT

# Current Files are Chesterfield or Leeds (comment one out)
# raw_data_file = "chesterfield_25-08-2021_09-00-00.csv"
raw_data_file = "leeds_01-01-2020_09-00-00.csv"

absolute_path_for_raw_data(raw_data_file)                                                           
columns = ['date_time', 'Location', 'full_name', 'order', 'amount', 'payment_type', 'card_number']  # Headers for the DF
# df = pd.read_csv(csv, header=None, names=columns)                                                   # Creates the DF

sort_time_to_postgre_format()
df 

In [ ]:


import pymysql 

#THIS IS AN EXAMPLE OF THE CONNECT WITH DB CLASS THAT I WAS DOING BEFORE...
#CHANGE THE VALUES IN THE TRY STATEMENT TO MAKE IT WORK WITH YOUR LOCAL DB 


### I did it with pymysql because I don't have a working postgre docker image atm) ... just replace every pymysql in the code for the other import  
# that handles postgre... connection methods are indentical.


#An Insert would be



class WithDB():

# SELECT [SQL] (2 arguments, SELECT = "*" TABLE = "table_name")

    def select(select, table):
        
        try:
            print("Connecting to DataBase...")
            host_name = "localhost"
            database_name = "raw_database"
            user_name = "root"
            user_password = "password"

            with pymysql.connect(
                        host = host_name,
                        database = database_name,
                        user = user_name,
                        password = user_password
                    ) as connection:
            
                cursor = connection.cursor()
                
                sql = f"SELECT {select} FROM {table}"
                cursor.execute(sql)
                table_data = cursor.fetchall()
                print(table_data)
                connection.commit()
        
        except Exception as ex:
            print("Failed to open connection, please make sure DB is Running")
            

def insert(row, table,columns):
        
        try:
            print("Connecting to DataBase...")
            host_name = "localhost"
            database_name = "raw_database"
            user_name = "root"
            user_password = "password"

            with pymysql.connect(
                        host = host_name,
                        database = database_name,
                        user = user_name,
                        password = user_password
                    ) as connection:
            
                cursor = connection.cursor()
                
                sql = f"INSERT INTO {table} {columns} VALUES (%s, %s, %s, %s, %s, %s, %s)"
                values = columns
                
                cursor.execute(sql,values)
                table_data = cursor.fetchall()
                print(table_data)
                connection.commit()
        
        except Exception as ex:
            print("Failed to open connection, please make sure DB is Running")
    

#The whole idea of the "WithDB" class is that I can be called like this for different scenarios
WithDB.select("*","raw_order")



# A row example.... edit for one value if it fails so you can check how it works
row = '(25/08/2021 09:00, Chesterfield,Richard Copeland, "Regular Flavoured iced latte - Hazelnut - 2.75, Large Latte - 2.45", 5.2, CARD, 5494173772652516)'
# the target table 
table = "raw_order"
#your table db columns  
columns = '(raw_id,date,location,full_name,orders,transaction_total,payment_type,card_number)'

#then you can call it like this:
WithDB.insert(row,table,columns)


# DATA PIPELINE ROUTE...

### 1. READ CSV FILE AS DATA FRAME

EXAMPLE OF A ROW AT THIS POINT: <br>
25/08/2021 09:00, Chesterfield,Richard Copeland, "Regular Flavoured iced latte - Hazelnut - 2.75, Large Latte - 2.45", 5.2, CARD, 5494173772652516

### 2. REMOVE THE COLUMNS NAME, CARD NUMBER

EXAMPLE OF A ROW AT THIS POINT:  <br>
25/08/2021 09:00, Chesterfield, "Regular Flavoured iced latte - Hazelnut - 2.75, Large Latte - 2.45", 5.2, CARD


### 3. CHANGE DATE FORMAT TO POSTQGRE'S FORMAT

EXAMPLE OF A ROW AT THIS POINT:  <br>

2021/08/25 09:00, Chesterfield,"Regular Flavoured iced latte - Hazelnut - 2.75, Large Latte - 2.45", 5.2, CARD


### 4. NORMALISE LOCATION AND PAYMENT_TYPE (A FUNCTION THAT CONNECTS TO DB AND CHECK IF THE LOCATION EXISTS RETURNING THE ID, IF NOT ADDS IT SHOULD BE CREATED)

EXAMPLE OF A ROW AT THIS POINT:  <br>

2021/08/25 09:00, 1 ,"Regular Flavoured iced latte - Hazelnut - 2.75, Large Latte - 2.45", 5.2, 2


### 5. EXTRACT PRODUCTS FROM EACH ORDER AND ADD THEM TO A SEPARATE DATA FRAME WITH [ORDER_ID] [PRODUCT_NAME]

EXAMPLE OF A ROW AT THIS POINT: <br>

2021/08/25 09:00, 1 ,1, 5.2, 2  <br>

AND THIS WILL BE THE ORDER FOR SAID ROW  <br>

Regular Flavoured iced latte - Hazelnut - 2.75
Large Latte - 2.45"


### 6. NORMALISE ORDER PRODUCTS (A FUNCTION THAT CONNECTS TO DB AND CHECK IF THE LOCATION EXISTS RETURNING THE ID, IF NOT ADDS IT SHOULD BE CREATED)

EXAMPLE OF A ROW AT THIS POINT: <br>

2021/08/25 09:00, 1 ,1, 5.2, 2 <br>

AND THIS WILL BE THE ORDER FOR SAID ROW <br>

1,1
1,2


### 7. INSERT THOSE TWO DF'S TO THE DB
